### ISSUE TITLE
Some problems with demo files and the script too

### ISSUE THREAD

**Issue by csakiistvan** [sergiodlopes/mailto#1]
I would like to use this lib, but i can't because it is not works to me. I use Drupal CMS with jQuery 1.10 and if I include this file (min and expand too) the console tell me: 

![mailto_lib_problem](https://cloud.githubusercontent.com/assets/2457274/6768871/58e39586-d082-11e4-92f7-786c1124c994.png)

Ok, I thought I look at the demo files, what I missed it. But unfortunately the demo files has a lot of bug
![mailto_jquery_plugin_and_example_and_lib_and_jquery_mailto_js_-_www_-____works_museum_www__and_museum_ _history__1872_commits_](https://cloud.githubusercontent.com/assets/2457274/6768884/99d61118-d082-11e4-9e3d-a4c98612f174.png)

**Comment by sergiodlopes** [comment]
Hi!
I think the last commit fixed the issues you're having.
Thanks for the heads up on the problem! :)

Please confirm if it's working now.

Thanks!

**Comment by csakiistvan** [comment]
Thanks, its works, good job :)
